### ISSUE TITLE
Guild Wars 2 module: Username for gold message not displayed correctly

### ISSUE THREAD

**Issue by MentalFS** [PhantomBot/custom-modules#28]
When displaying the ```string guildwars2.session_gold.earned```: 

> ```「Guild Wars²」 me.mast3rplan.phantombot.cache.UsernameCache@1bad7b6 erhielt 4g 43s 00c in den vergangenen 5 Minuten! ```

[Code line](https://github.com/PhantomBot/custom-modules/blob/93f8ea5f201916cde7e2c8dacac6b0e172cf9f1f/guildwars2/games/guildwars2.js#L262)

Using PhantomBot Version: 2.3.5.2 (Revision: c671b201) + GuildWars2 module, no core files changed.

**Comment by MentalFS** [comment]
It's can be solved by adding this 2 lines before:

>``` var username = $.username.resolve($.channelName); ```

**Comment by Nekress** [comment]
I am currently on my vacation (12 february - 14 march) and will have exams immedately after. I will fix it 16 march.
