### ISSUE TITLE
Issue with Pokemon code

### ISSUE THREAD

**Issue by Monsterlax** [PhantomBot/custom-modules#29]
Ive been using an old code for the pokemon for a while now because the new codes seem to always be bugged with 
![image](https://cloud.githubusercontent.com/assets/22845261/23325242/fc2e4eaa-fac1-11e6-8ca0-eac58cb79bfb.png)

I do not know what is causing it. I have downloaded fresh versions of both the bot and the pokemon files many times and nothing seems to fix it.

Please let me know if you have any solutions to this problem.
Thank you,
Monster

**Comment by phantomindex** [comment]
I just finished catching all the bugs and fixed the issue with it not working. Sorry about that. It's hard to keep up with both waifu and pokemon.
