### ISSUE TITLE
ChallongeHandler.js ERROR

### ISSUE THREAD

**Issue by X00LA** [PhantomBot/custom-modules#31]
I translated the ChallongeHandler module and when I tested it I get the following errors when I type !match and !report.

[ERROR] [init.js:317] (hook.call, command, ./handlers/challongeHandler.js) TypeError: Cannot read property "state" from undefined
[ERROR] [init.js:317] (hook.call, command, ./handlers/challongeHandler.js) TypeError: Cannot call method "get" of undefined

I also get no response, when I type !challongekey MY_API_KEY into chat. The only way it works is to type the command directly into the console.

Regards

**Comment by phantomindex** [comment]
Interesting.. Well I just put in a lang file for it so try translating it from there and see what happens. But note that if you haven't created a tournament before on that account some commands will not work. like !last !match and !report.

Because it uses data from an older tournament. it's also safer to use challonge key in console so you don't give out your api key.

**Comment by X00LA** [comment]
I created a account and a tournament to test it.
The API Keys was accepted from the Bot, but only when I write the command directly into the console.
The other commands doesn't work. Tried it 4 times with 4 different tounaments I created.

**Comment by phantomindex** [comment]
So I assume it's the !challongekey not properly entering the API?

**Comment by X00LA** [comment]
Hm, that's interesting and confusing. Can't retrace why. My PC has all necessary ports open and also my router. The Bot itself works without any problems with the connections. The log files giving me no hints what's wrong.

**Comment by phantomindex** [comment]
Do you mind giving me your api key and i test it out?

**Comment by X00LA** [comment]
No Problem.
VVMRtMXfiI4xlO7EZTSMvlCLMxkUPrHaajWBICZv
It's the key of my Main Account where I tested the first time.

**Comment by phantomindex** [comment]
I tested your data and it works. I also added something new so when you switch the api to a different account it will wipe data from the db so it wont conflict.

!match is only meant to retrieve the last match in a IN-PROGRESS tournament. If there are no tournaments in progress it will just not retrieve it.

**Comment by X00LA** [comment]
Ok, thank you. Looks like there's an issue with my connection. Hm. Need to look where's the problem.
I used it only to test the translation.
The important thing is that it works for the end user. ;)

**Comment by phantomindex** [comment]
these errors are normal when you don't have a tournament running, so dont worry.
[ERROR] [init.js:317] (hook.call, command, ./handlers/challongeHandler.js) TypeError: Cannot read property "state" from undefined
[ERROR] [init.js:317] (hook.call, command, ./handlers/challongeHandler.js) TypeError: Cannot call method "get" of undefined
