### ISSUE TITLE
Pokemon System setpokemon Error message displays $1 instead of username

### ISSUE THREAD

**Issue by sk8rdude461** [PhantomBot/custom-modules#33]
Title kinda says it all.

In the pokemon system:
`            $.say($.lang.get('pwaifugames.harem.kick404'));`
Needs to be replaced with:
`            $.say($.lang.get('pwaifugames.harem.kick404',$.userPrefix(username, true)));`

As it currently shows:

> $1 that Pokémon is not in your team!

Instead of:
> @\<user\>, that Pokémon is not in your team!

**Comment by phantomindex** [comment]
yeah i figured i'd remove it instead. thanks!
