### ISSUE TITLE
waifu installation instructions

### ISSUE THREAD

**Issue by wyrde** [PhantomBot/custom-modules#40]
In readme files for waifu and pokemon modules, installation step 4 is

> Replace the web folder in your root folder of Phantombot with the one that comes with this.

Where is the web folder that comes with this? Or which this is that referring to?

Instructions unclear, waifu stuck in doge-house.

More seriously, is the line seems left over from an older version?

**Comment by phantomindex** [comment]
the web folder was kinda removed by mistake, it's not important per say, but I'll add it back in a bit.

**Comment by phantomindex** [comment]
Fixed
