### ISSUE TITLE
Pokémon Script Issues

### ISSUE THREAD

**Issue by choseh** [PhantomBot/custom-modules#45]
Hey, 

with the latest (2.3.8) version of phantombot, some of the triggers don't do anything. !pokefile won't work in chat or via whisper. Is this still working? I'd love to see this working again.

Best,
Alex

**Comment by Zelakto** [comment]
Hi there,
I'm going to need more information. Can you check your error logs, or even try upgrading to the latest version of the bot? Thank you.

**Comment by choseh** [comment]
Hey Zelakto,
thanks for asking, but I had things sorted out after a while back then. This can be closed :)

best,
Alex
