### ISSUE TITLE
!buycandy discounting more than it should

### ISSUE THREAD

**Issue by GrandmasterMeio** [PhantomBot/custom-modules#50]
Hello! Thanks for the great script.
I think I found a bug with the !buycandy. Apparently, if the bought is too big (like 20 candies f.x. or even the !buycandy alone that use every point to buy candies), the script don't know how to save the difference. 

So, let's say the price is 25 per candy. If the difference after buying a certain amount of candies is less 25 points, the system simply make those leftover points disappear and the user ends with 0 points (and every candy that was bought). Anyone have an idea about how to fix it?

Thank you!

**Comment by IllusionaryOne** [comment]
All bug reports go to the Forums.
